Search autocomplete
UTDallasEPICS/Comet-Cupboard pull request #74
Opened 2024-10-26 00:05 UTC by emoryjgrubbs

the autocomplete functionality should be working for both items and carts (the correct component is on both pages), but the searchterm isn't displayed on the verify carts page because there is already content there.

for both carts and items it's returning the id that will be searched for

the filtering is done through api calls .../filtered[resultType].get.ts
i've turned off the date check on the cart calls, so that can be implemented with the list of carts solution

i'm not sure about the styling right now, it's inline with the sources, but leaves a lot of whitespace on the sides. i may take another look at it later

changed selection highlight color. for now it's utd-orange, but i'd be happy with pretty much anything from our color palate (i was just tired of looking at the blue that didn't match)

2024-10-27 02:25 UTC, CrazEpic requested changes
The functionality is looking good. Left some comments about refactoring code.

Would recommend left aligning the search recommendations. Here's Youtube's
![image](https://github.com/user-attachments/assets/9e976ff6-e0af-46e7-acc7-69ee10dac82e)

Would recommend placing the API calls for "searching" in the corresponding flow folder so we don't duplicate code. For example, GET /api/page-controls/carts is pretty much the same as GET /api/verification/pendingCarts. 

Two ways we can do this for each searching: 
1. One API call. Have a parameter like "search" = true in order to only return relevant search fields.
2. Two API calls. One for full version and one for search version.

2024-10-27 02:25 UTC, CrazEpic commented on server/api/page-controls/carts.get.ts
> +    const staleCutOff = new Date(currentTime.valueOf() - 1800000); //current time -30 minutes
Change comment to - 30 minutes
Or 1000 * 60 * 30

2024-10-27 02:25 UTC, CrazEpic commented on server/api/page-controls/carts.get.ts
might need to put this API call in /verification, functionality is nearly the same as GET pendingCarts

2024-10-27 02:25 UTC, CrazEpic commented on server/api/page-controls/filteredCarts.get.ts
we should add a parameter for queries in GET carts API call instead of creating a new file

2024-10-27 02:25 UTC, CrazEpic commented on server/api/page-controls/filteredCarts.get.ts
actually, I think I see what you're trying to do (just getting cart names only rather than passing back whole carts), will address in a general comment

2024-10-27 02:25 UTC, CrazEpic commented on server/api/page-controls/items.get.ts
similar comment to carts

2024-10-27 02:25 UTC, CrazEpic commented on server/api/page-controls/filteredItems.get.ts
similar comment to filterCarts

2024-10-27 02:25 UTC, CrazEpic commented on components/ControlsSearch.vue
> +                ComboboxOption( v-for="result in filteredResults" :key="result.name" :value="result" ).p-1.text-center.text-xl.cursor-pointer.text-wrap.hover_bg-cupboard-lg
I don't like the whitespace from text-center. I prefer text left align because that's how the query is aligned too.

2024-10-27 02:28 UTC, CrazEpic commented on server/api/page-controls/carts.get.ts
> +    const staleCutOff = new Date(currentTime.valueOf() - 1800000); //current time -30 minutes
Saw this in retrospect. It looks different. Ignore the comment

2024-10-31 04:05 UTC, emoryjgrubbs commented
left aligned the autocomplete results, with some padding and increased size so they line up with what you type
![2024-10-30T17:59:59,006677140-05:00](https://github.com/user-attachments/assets/698bf396-9413-480f-9959-b39d58d3418f)

i also merged the two api calls in the search module (every record contains '') but i'm going to wait to merge with pendingCarts.get till i talk to you tomorrow so we can figure out what's best

2024-10-31 20:55 UTC, merged